---
title: "One DEM Tile"
author: "Anna Talucci"
date: '2022-06-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# OVerview

# Packages 

```{r}
library(sp) 
library(raster)
library(rgdal)
library(sf)

```


# Data
```{r}
fire = st_read("../data/NBAC/nbac_2014_r9_20210810/nbac_2014_r9_20210810.shp", "nbac_2014_r9_20210810")
```

## DEM First Last
```{r}
demfirst<-raster("../data/N60W130-N70W120_FABDEM_V1-0/N60W121_FABDEM_V1-0.tif")
demfirst
```
```{r}
demlast<-raster("../data/N60W130-N70W120_FABDEM_V1-0/N69W130_FABDEM_V1-0.tif")
demlast
```

```{r}

plot(demfirst)
plot(demlast)
```

## DEM 1-3
```{r}
dem1<-raster("../data/demtiff3/N60W121_FABDEM_V1-0.tif")
dem1
```

```{r}
dem2<-raster("../data/demtiff3/N60W122_FABDEM_V1-0.tif")
dem2
```

```{r}
dem3<-raster("../data/demtiff3/N60W123_FABDEM_V1-0.tif")
dem3
```

# Projections
```{r}
projection<-crs(dem)
projection
```

```{r}
fire_proj = st_crs(fire)
```

```{r}
equalArea = st_crs("+proj=aea +lat_1=50 +lat_2=70 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs" )
```
## Call all Tiffs

```{r}


mosaicList <- function(rasList){

  #Internal function to make a list of raster objects from list of files.
  ListRasters <- function(list_names) {
    raster_list <- list() # initialise the list of rasters
    for (i in 1:(length(list_names))){ 
      grd_name <- list_names[i] # list_names contains all the names of the images in .grd format
      raster_file <- raster::raster(grd_name)
      raster_file <- projectRaster(raster_file, snap, method = "ngb")
          }
    raster_list <- append(raster_list, raster_file) # update raster_list at each iteration
  }

  #convert every raster path to a raster object and create list of the results
  raster.list <-sapply(rasList, FUN = ListRasters)

  # edit settings of the raster list for use in do.call and mosaic
  names(raster.list) <- NULL
  #####This function deals with overlapping areas
  raster.list$fun <- sum
  #raster.list$tolerance <- 0.1

  #run do call to implement mosaic over the list of raster objects.
  mos <- do.call(raster::mosaic, raster.list)

  #set crs of output
  crs(mos) <- crs(x = raster(rasList[1]))
  return(mos)
}

raster_files <- list.files(path ="../data/demtiff3/",pattern = ".tif$",full.names = TRUE )
snap <- raster(resolution = c( 0.0002777778,  0.0002777778), xmn = -123.0003, xmx = -120.0003, ymn = 60.00014, ymx = 61.00014,  crs = projection) 
dem_layer <- mosaicList(raster_files )
```
extent     : -121.0003, -120.0003, 60.00014, 61.00014  (xmin, xmax, ymin, ymax)
extent     : -130.0003, -129.0003, 69.00014, 70.00014  (xmin, xmax, ymin, ymax)


```{r}
plot(dem_layer)
```

# Write DEM test layer to file
```{r eval=FALSE, include=FALSE}
writeRaster(dem_layer, filename="../outputs/DEMtest.shp", format="GTiff",)
```


# Convert DEM to equal area projection
```{r}
DEM_eaproj <- projectRaster(dem_layer, crs = crs("+proj=aea +lat_1=50 +lat_2=70 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs" ))

```

```{r}
DEM_eaproj
```

```{r}
plot(DEM_eaproj)
```

# Write DEM test layer to file
```{r eval=FALSE, include=FALSE}
writeRaster(DEM_eaproj, filename="../outputs/DEMtestEqualArea.shp", format="GTiff",)
```