---
title: "NWT Field DEM"
author: "Anna Talucci"
date: '2022-06-22'
output: html_document
---

# Overview

Combine DEM tiles for NWT field sites latitude and longitude range 

Limit to Taiga Shield (15 tiles)

# Packages 

```{r}
library(sp) 
library(raster)
library(rgdal)
library(sf)

```


# Data
Latitude range 60.2151 to 64.1714
Longitude Range -121.0111 to  -113.0163

For shield only (smaller area)
Latitude 62.3306 to 64.1714
Longitude  -117.2655 to -113.0163

N60W120-N70W110_FABDEM_V1-0

```{r}
N62W117<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N62W117_FABDEM_V1-0.tif")
N62W117
```

```{r}
N63W117<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N63W117_FABDEM_V1-0.tif")
N64W117<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N64W117_FABDEM_V1-0.tif")
```

```{r}
N62W116<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N62W116_FABDEM_V1-0.tif")
N63W116<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N63W116_FABDEM_V1-0.tif")
N64W116<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N64W116_FABDEM_V1-0.tif")
```

```{r}
N62W115<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N62W115_FABDEM_V1-0.tif")
N63W115<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N63W115_FABDEM_V1-0.tif")
N64W115<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N64W115_FABDEM_V1-0.tif")
```

```{r}
N62W114<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N62W114_FABDEM_V1-0.tif")
N63W114<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N63W114_FABDEM_V1-0.tif")
N64W114<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N64W114_FABDEM_V1-0.tif")
```

```{r}
N62W113<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N62W113_FABDEM_V1-0.tif")
N63W113<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N63W113_FABDEM_V1-0.tif")
N64W113<-raster("../data/N60W120-N70W110_FABDEM_V1-0/N64W113_FABDEM_V1-0.tif")
```

```{r}
N64W113
```
# Projections
```{r}
projection<-crs(N64W113)
projection
```
# Mosaic Raster

## Function
```{r}


mosaicList <- function(rasList){

  #Internal function to make a list of raster objects from list of files.
  ListRasters <- function(list_names) {
    raster_list <- list() # initialise the list of rasters
    for (i in 1:(length(list_names))){ 
      grd_name <- list_names[i] # list_names contains all the names of the images in .grd format
      raster_file <- raster::raster(grd_name)
      raster_file <- projectRaster(raster_file, snap, method = "ngb")
          }
    raster_list <- append(raster_list, raster_file) # update raster_list at each iteration
  }

  #convert every raster path to a raster object and create list of the results
  raster.list <-sapply(rasList, FUN = ListRasters)

  # edit settings of the raster list for use in do.call and mosaic
  names(raster.list) <- NULL
  #####This function deals with overlapping areas
  raster.list$fun <- sum
  #raster.list$tolerance <- 0.1

  #run do call to implement mosaic over the list of raster objects.
  mos <- do.call(raster::mosaic, raster.list)

  #set crs of output
  crs(mos) <- crs(x = raster(rasList[1]))
  return(mos)
}
```

```{r}
raster_files <- list.files(path ="../data/DEMFieldNWTShield/",pattern = ".tif$",full.names = TRUE )
snap <- raster(resolution = c( 0.0002777778,  0.0002777778), xmn = -117.0003, xmx = -112.0003, ymn = 62.00014, ymx = 65.00014,  crs = projection) 
dem_layer <- mosaicList(raster_files )
```

```{r}
plot(dem_layer)
```

```{r eval=FALSE, include=FALSE}
writeRaster(dem_layer, filename="../outputs/DEMFieldNWTShield.tif", format="GTiff",)
```