---
title: "DEMMosaicSKField"
author: "Anna Talucci"
date: '2022-07-15'
output: html_document
---






# Overview

Combine DEM tiles for SK field sites latitude and longitude range from FAB DEM from Compernicus (bare earth)

Lat long range for SK
Latitude (N)
[1] 53.1911
[1] 57.3646

Longitude (W)
[1] -111.3801
[1] -88.612

# Packages 

```{r}
library(terra)
library(gdalUtilities)
library(sf)
```


# Data

```{r}
first<-rast("../data/DEMFieldSK/N53W088_FABDEM_V1-0.tif")
last<-rast("../data/DEMFieldSK/N57W112_FABDEM_V1-0.tif")
```

```{r}
first
```

```{r}
last
```

# Projections
```{r}
projection<-crs(last)
projection
```
# Masaic with Terra 

## Make list of rasters
```{r}
rlist <- list.files(path ="../data/DEMFieldSK/",pattern = ".tif$",full.names = TRUE )
```

## Define as rasters
```{r}
r <- lapply(rlist, rast)
```

## Make a spatial raster collection
```{r}

rsrc <- sprc(r)
```

##  Mosaic
```{r}
m <- mosaic(rsrc)
```


## Plot DEM

```{r eval=FALSE, include=FALSE}
plot(m)
```

```{r eval=FALSE, include=FALSE}
writeRaster(m, filename="../outputs/FieldDEM/DEMFieldSK.tif")
```