---
title: "DEMMosaicFirstLandscape"
author: "Anna Talucci"
date: '2022-07-08'
output: html_document
---


# Overview

Combine DEM tiles for NWT field sites latitude and longitude range 

Limit to Taiga Shield (15 tiles)

# Packages 

```{r}
library(sp) 
library(raster)
library(rgdal)
library(sf)

```


N64W146_FABDEM_V1-0

```{r}
N64W146<-raster("../data/FABDEMTiles_Landscape1/N64W146_FABDEM_V1-0.tif")
N66W148<-raster("../data/FABDEMTiles_Landscape1/N66W148_FABDEM_V1-0.tif")
```

```{r}
N64W146
```

```{r}
N66W148
```

# Projections
```{r}
projection<-crs(N66W148)
projection
```
# Mosaic Raster

## Function
```{r}


mosaicList <- function(rasList){

  #Internal function to make a list of raster objects from list of files.
  ListRasters <- function(list_names) {
    raster_list <- list() # initialise the list of rasters
    for (i in 1:(length(list_names))){ 
      grd_name <- list_names[i] # list_names contains all the names of the images in .grd format
      raster_file <- raster::raster(grd_name)
      raster_file <- projectRaster(raster_file, snap, method = "ngb")
          }
    raster_list <- append(raster_list, raster_file) # update raster_list at each iteration
  }

  #convert every raster path to a raster object and create list of the results
  raster.list <-sapply(rasList, FUN = ListRasters)

  # edit settings of the raster list for use in do.call and mosaic
  names(raster.list) <- NULL
  #####This function deals with overlapping areas
  raster.list$fun <- sum
  #raster.list$tolerance <- 0.1

  #run do call to implement mosaic over the list of raster objects.
  mos <- do.call(raster::mosaic, raster.list)

  #set crs of output
  crs(mos) <- crs(x = raster(rasList[1]))
  return(mos)
}
```

```{r}
raster_files <- list.files(path ="../data/FABDEMTiles_Landscape1/",pattern = ".tif$",full.names = TRUE )
snap <- raster(resolution = c( 0.0002777778,  0.0002777778), xmn = -148.0003, xmx = -145.0003, ymn = 64.00014, ymx = 67.00014,  crs = projection) 
dem_layer <- mosaicList(raster_files )
```

```{r}
plot(dem_layer)
```

```{r eval=FALSE, include=FALSE}
writeRaster(dem_layer, filename="../outputs/DEMAKLandscape1.tif", format="GTiff",)
```

# Masaic with Terra 

## Make list of rasters
```{r}
rlist <- list.files(path ="../data/FABDEMTiles_Landscape1/",pattern = ".tif$",full.names = TRUE )
```

## Define as rasters
```{r}
r <- lapply(rlist, rast)
```

## Make a spatial raster collection
```{r}

rsrc <- sprc(r)
```

##  Mosaic
```{r}
m <- mosaic(rsrc)
```

## Plot DEM

```{r}
plot(m)
```

```{r eval=FALSE, include=FALSE}
writeRaster(m, filename="../outputs/DEMAKLandscape1_v2.tif")
```